"use client";

import { useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { SectionHeading } from "@/components/ui/section-heading";

const parameters={
  pH:{accent:"#22D3EE",bg:"#072026",pattern:"radial-gradient(circle at 20% 30%,rgba(34,211,238,.18),transparent 28%), repeating-radial-gradient(circle at 70% 75%,rgba(34,211,238,.08) 0 2px,transparent 3px 20px)",meaning:"Root-zone availability",copy:"pH influences nutrient availability and is one of the core root-zone signals monitored by Hydro AI.",role:"Fluid and nutrient context"},
  EC:{accent:"#3B82F6",bg:"#09152d",pattern:"linear-gradient(125deg,transparent 0 45%,rgba(59,130,246,.15) 46% 47%,transparent 48% 100%),radial-gradient(circle at 75% 30%,rgba(59,130,246,.2),transparent 28%)",meaning:"Dissolved ionic concentration",copy:"Electrical conductivity provides a useful signal for dissolved ionic concentration and nutrient-management decisions.",role:"Electrical / data context"},
  FLOW:{accent:"#22D3EE",bg:"#071e21",pattern:"repeating-linear-gradient(0deg,transparent 0 17px,rgba(34,211,238,.08) 18px 20px),radial-gradient(circle at 70% 50%,rgba(34,211,238,.18),transparent 31%)",meaning:"Hydraulic operation",copy:"Flow provides insight into hydraulic operation and helps identify circulation problems.",role:"Hydraulic context"},
  TEMP:{accent:"#f59e0b",bg:"#241607",pattern:"radial-gradient(ellipse at 28% 50%,rgba(245,158,11,.28),transparent 35%),repeating-linear-gradient(15deg,transparent 0 18px,rgba(245,158,11,.07) 19px 21px)",meaning:"Thermal state",copy:"Temperature shapes biological and hydraulic context across a hydroponic system.",role:"Thermal context"},
  HUMIDITY:{accent:"#8B5CF6",bg:"#171027",pattern:"radial-gradient(circle at 28% 30%,rgba(139,92,246,.18),transparent 30%),radial-gradient(circle at 70% 65%,rgba(139,92,246,.11),transparent 25%)",meaning:"Atmospheric state",copy:"Humidity is an environmental signal that gains meaning alongside temperature, plant state and time.",role:"Atmospheric context"},
  LIGHT:{accent:"#facc15",bg:"#261f07",pattern:"repeating-linear-gradient(105deg,transparent 0 18px,rgba(250,204,21,.12) 19px 21px),radial-gradient(circle at 20% 15%,rgba(250,204,21,.2),transparent 30%)",meaning:"Photonic input",copy:"Light is a measurable crop input that becomes more useful when paired with plant and environmental records.",role:"Photonic context"},
  AI:{accent:"#8B5CF6",bg:"#130c20",pattern:"radial-gradient(circle at 25% 28%,rgba(139,92,246,.21),transparent 23%),radial-gradient(circle at 75% 65%,rgba(34,211,238,.12),transparent 28%)",meaning:"Decision support",copy:"AI can turn synchronized signals into patterns and recommendations—but only after careful validation.",role:"Neural / decision context"}
};

export function ParameterExplorer(){const [selected,setSelected]=useState<keyof typeof parameters>("pH");const reduce=useReducedMotion();const active=parameters[selected];const style={"--theme-bg":active.bg,"--accent":active.accent,"--theme-pattern":active.pattern,"--glow":`${active.accent}33`} as React.CSSProperties;return <section className="section"><SectionHeading eyebrow="Signature interaction" title="Explore the signals behind a living system." copy="Select a parameter to see how a different class of measurement changes the technical context."/><div style={style} className="technical-surface card mt-10 overflow-hidden"><div className="flex gap-2 overflow-x-auto border-b border-white/10 p-4">{Object.keys(parameters).map(key=><button onClick={()=>setSelected(key as keyof typeof parameters)} className={`shrink-0 rounded-md px-3 py-2 text-sm font-bold ${selected===key?"bg-white text-[#06110e]":"bg-white/5 text-white/70 hover:bg-white/10"}`} key={key}>{key}</button>)}</div><motion.div key={selected} initial={reduce?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} className="grid gap-8 p-7 md:grid-cols-[.82fr_1.18fr]"><div className="grid min-h-52 place-items-center rounded-xl border border-white/10 bg-black/10"><div className="relative grid h-28 w-28 place-items-center rounded-full border border-[var(--accent)]/70"><span className="text-3xl font-black text-[var(--accent)]">{selected}</span><i className="absolute -left-5 top-1/2 h-1.5 w-1.5 rounded-full bg-[var(--accent)]"/><i className="absolute -right-5 top-1/3 h-1.5 w-1.5 rounded-full bg-[var(--accent)]"/></div></div><div><p className="eyebrow text-[var(--accent)]">{active.role}</p><h3 className="mt-2 text-3xl font-bold">{active.meaning}</h3><p className="muted mt-4 leading-relaxed">{active.copy}</p><p className="mt-7 text-sm font-bold">Hydro AI role <span className="muted font-normal">— measure context before making a decision.</span></p></div></motion.div></div></section>}
